#
# --------------------------------------------------------------------------------
# SPDX-FileCopyrightText: 2024-2026 Martin Jan Köhler and Harald Pretl
# Johannes Kepler University, Institute for Integrated Circuits.
#
# This file is part of KPEX 
# (see https://github.com/iic-jku/klayout-pex).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# SPDX-License-Identifier: GPL-3.0-or-later
# --------------------------------------------------------------------------------
#

"""
Lazy access to the generated PEX25D protobuf modules.

The ``*_pb2.py`` modules are produced by the build (``build.sh`` / CMake) and are ``.gitignore``d,
so importing them at module scope would make ``--help`` fail on a fresh checkout.
Every accessor here imports on demand, ``ImportError``s are turned into actionable messages instead of tracebacks.
"""

from __future__ import annotations

import functools
from typing import *


class ProtobufNotGeneratedError(RuntimeError):
    """The generated PEX25D protobuf modules are not importable."""


def _import(module_name: str) -> Any:
    import importlib
    try:
        return importlib.import_module(module_name)
    except ImportError as e:
        raise ProtobufNotGeneratedError(
            f"Can't import the generated PEX25D protobuf module '{module_name}'.\n"
            f"The *_pb2.py modules are generated by the build and are not checked in — "
            f"run ./build.sh (or the CMake target) and try again.\n"
            f"Original error: {e}"
        ) from e
    except Exception as e:
        # A gencode/runtime version mismatch raises protobuf's own VersionError,
        # which is not an ImportError and would otherwise surface as a traceback
        # from deep inside the generated module. It means the *_pb2.py files were
        # produced by a different protoc than the protobuf runtime in use.
        if type(e).__name__ != 'VersionError':
            raise
        raise ProtobufNotGeneratedError(
            f"The generated module '{module_name}' does not match the installed "
            f"protobuf runtime — re-run ./build.sh (or the CMake target) to "
            f"regenerate it.\nOriginal error: {e}"
        ) from e


_PACKAGE = 'klayout_pex_protobuf.kpex.pex25d'
_MODULE_PREFIX = 'pex25d_'
_MODULE_SUFFIX = '_pb2'


@functools.cache
def schema_names() -> Tuple[str, ...]:
    """
    The PEX25D schema names the build generated, e.g. ``('diagnostics', …)``.

    Discovered in the generated package rather than listed here, so that adding
    or removing a ``.proto`` needs no edit: the module naming convention
    ``pex25d_<name>_pb2`` is the whole mapping.
    """
    import pkgutil
    package = _import(_PACKAGE)
    return tuple(sorted(
        name[len(_MODULE_PREFIX):-len(_MODULE_SUFFIX)]
        for _, name, _ in pkgutil.iter_modules(package.__path__)
        if name.startswith(_MODULE_PREFIX) and name.endswith(_MODULE_SUFFIX)
    ))


def schema_module(name: str) -> Any:
    """The generated module of one schema, see :func:`schema_names`."""
    if name not in schema_names():
        raise ValueError(f"PEX25D has no schema '{name}'; the build generated "
                         f"{', '.join(schema_names())}")
    return _import(f"{_PACKAGE}.{_MODULE_PREFIX}{name}{_MODULE_SUFFIX}")


@functools.cache
def pex25d_file_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_file_pb2')


@functools.cache
def pex25d_scene_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_scene_pb2')


@functools.cache
def pex25d_dielectric_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_dielectric_pb2')


@functools.cache
def pex25d_geometry_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_geometry_pb2')


@functools.cache
def pex25d_terminal_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_terminal_pb2')


@functools.cache
def pex25d_diagnostics_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_diagnostics_pb2')


@functools.cache
def pex25d_source_ref_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_source_ref_pb2')


def kind_for_message(message: Any) -> 'ArtifactKind':  # noqa: F821 (avoid import cycle)
    """
    Return the :class:`ArtifactKind` a generated message holds.

    Derived from :func:`message_class_for_kind`, so that a message renamed in
    the schema is one edit rather than two that can drift apart.
    """
    from .artifact import ArtifactKind

    for kind in ArtifactKind:
        try:
            message_class = message_class_for_kind(kind)
        except ValueError:  # a kind that describes no message, i.e. AUTO
            continue
        if message.DESCRIPTOR is message_class.DESCRIPTOR:
            return kind

    raise ValueError(f"'{message.DESCRIPTOR.name}' is not a PEX25D artifact message")


def message_class_for_kind(kind: 'ArtifactKind') -> Any:  # noqa: F821 (avoid import cycle)
    """Return the generated message class matching an :class:`ArtifactKind`."""
    from .artifact import ArtifactKind

    match kind:
        case ArtifactKind.FILE:
            return pex25d_file_pb2().PEX25DFile
        case ArtifactKind.SCENE:
            return pex25d_scene_pb2().PEX25DScene
        case _:
            raise ValueError(f"No message class for artifact kind {kind}")
