#
# --------------------------------------------------------------------------------
# SPDX-FileCopyrightText: 2024-2026 Martin Jan Köhler and Harald Pretl
# Johannes Kepler University, Institute for Integrated Circuits.
#
# This file is part of KPEX 
# (see https://github.com/iic-jku/klayout-pex).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# SPDX-License-Identifier: GPL-3.0-or-later
# --------------------------------------------------------------------------------
#

"""
Lazy access to the generated PEX25D protobuf modules.

The ``*_pb2.py`` modules are produced by the build (``build.sh`` / CMake) and are ``.gitignore``d,
so importing them at module scope would make ``--help`` fail on a fresh checkout.
Every accessor here imports on demand, ``ImportError``s are turned into actionable messages instead of tracebacks.
"""

from __future__ import annotations

import functools
from typing import *


class ProtobufNotGeneratedError(RuntimeError):
    """The generated PEX25D protobuf modules are not importable."""


def _import(module_name: str) -> Any:
    import importlib
    try:
        return importlib.import_module(module_name)
    except ImportError as e:
        raise ProtobufNotGeneratedError(
            f"Can't import the generated PEX25D protobuf module '{module_name}'.\n"
            f"The *_pb2.py modules are generated by the build and are not checked in — "
            f"run ./build.sh (or the CMake target) and try again.\n"
            f"Original error: {e}"
        ) from e
    except Exception as e:
        # A gencode/runtime version mismatch raises protobuf's own VersionError,
        # which is not an ImportError and would otherwise surface as a traceback
        # from deep inside the generated module. It means the *_pb2.py files were
        # produced by a different protoc than the protobuf runtime in use.
        if type(e).__name__ != 'VersionError':
            raise
        raise ProtobufNotGeneratedError(
            f"The generated module '{module_name}' does not match the installed "
            f"protobuf runtime — re-run ./build.sh (or the CMake target) to "
            f"regenerate it.\nOriginal error: {e}"
        ) from e


@functools.cache
def pex25d_file_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_file_pb2')


@functools.cache
def pex25d_scene_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_scene_pb2')


@functools.cache
def pex25d_dielectric_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_dielectric_pb2')


@functools.cache
def pex25d_geometry_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_geometry_pb2')


@functools.cache
def pex25d_terminal_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_terminal_pb2')


@functools.cache
def pex25d_diagnostics_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_diagnostics_pb2')


@functools.cache
def pex25d_source_ref_pb2() -> Any:
    return _import('klayout_pex_protobuf.kpex.pex25d.pex25d_source_ref_pb2')


def message_class_for_kind(kind: 'ArtifactKind') -> Any:  # noqa: F821 (avoid import cycle)
    """Return the generated message class matching an :class:`ArtifactKind`."""
    from .artifact import ArtifactKind

    match kind:
        case ArtifactKind.FILE:
            return pex25d_file_pb2().PEX25DFile
        case ArtifactKind.SCENE:
            return pex25d_scene_pb2().PEX25DScene
        case _:
            raise ValueError(f"No message class for artifact kind {kind}")
