#
# --------------------------------------------------------------------------------
# SPDX-FileCopyrightText: 2024-2025 Martin Jan Köhler and Harald Pretl
# Johannes Kepler University, Institute for Integrated Circuits.
#
# This file is part of KPEX 
# (see https://github.com/iic-jku/klayout-pex).
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
# SPDX-License-Identifier: GPL-3.0-or-later
# --------------------------------------------------------------------------------
#
from enum import StrEnum
import time
from typing import *

import os
import subprocess

from ..log import (
    info,
    # warning,
    rule,
    subproc,
)
from ..version import __version__


class MagicPEXMode(StrEnum):
    CC = "CC"
    RC = "RC"
    R = "R"
    DEFAULT = CC


class MagicShortMode(StrEnum):
    NONE = "none"
    RESISTOR = "resistor"
    VOLTAGE = "voltage"
    DEFAULT = NONE


class MagicMergeMode(StrEnum):
    NONE = "none"                  # don't merge parallel devices
    CONSERVATIVE = "conservative"  # merge devices with same L, W
    AGGRESSIVE = "aggressive"      # merge devices with same L
    DEFAULT = NONE


def prepare_magic_script(gds_path: str,
                         cell_name: str,
                         run_dir_path: str,
                         script_path: str,
                         output_netlist_path: str,
                         pex_mode: MagicPEXMode,
                         c_threshold: float,
                         r_threshold: float,
                         threshold: float,
                         min_res: float,
                         min_delay: float,
                         halo: Optional[float],
                         short_mode: MagicShortMode,
                         merge_mode: MagicMergeMode):
    gds_path = os.path.abspath(gds_path)
    run_dir_path = os.path.abspath(run_dir_path)
    output_netlist_path = os.path.abspath(output_netlist_path)

    halo_scale = 200.0

    # NOTE: do not that those are doing nothing useful:
    #       extract do resistance
    #       ext2spice rthresh {r_threshold}
    #
    #       see https://github.com/martinjankoehler/magic/issues/4#issuecomment-3381935719

    has_res = pex_mode in (MagicPEXMode.RC, MagicPEXMode.R)
    has_cap = pex_mode in (MagicPEXMode.RC, MagicPEXMode.CC)
    # Per corner extraction modes
    ext_coupling: str = "do" if has_cap else "no"
    ext_cap: str = "do" if has_cap else "no"
    ext_res: str = "do" if has_res else "no"

    script_lines: list[str|None] = [
        f"# Generated by kpex {__version__}",
        "crashbackups stop",
        "drc off",
        f"gds read {gds_path}",
        f"load {cell_name}",
        "select top cell",
        f"flatten {cell_name}_flat",
        f"load {cell_name}_flat",
        f"cellname delete {cell_name} -noprompt",
        f"cellname rename {cell_name}_flat {cell_name}",
        "select top cell",
        f"extresist threshold {threshold}" if threshold is not None else None,
        f"extresist minres {min_res}" if min_res is not None else None,
        f"extresist mindelay {min_delay}" if min_delay is not None else None,
        f"extract path {run_dir_path}",
        f"extract halo {round(halo * halo_scale)}" if halo is not None else None,
        f"extract {ext_cap} capacitance",
        f"extract {ext_coupling} coupling",
        f"extract {ext_res} resistance",
        "extract do unique",
        "extract all",
        f"ext2spice short {short_mode}",
        f"ext2spice merge {merge_mode}",
        f"ext2spice cthresh {c_threshold}" if has_cap else None,
        "ext2spice extresist on" if has_res else None,
        "ext2spice subcircuits top on",
        "ext2spice format ngspice",
        f"ext2spice -p {run_dir_path} -o {output_netlist_path}",
        "quit -noprompt"
    ]

    # filter out all empty strings and write out script
    script: str = "\n".join(filter(None, script_lines)) + "\n"

    with open(script_path, 'w', encoding='utf-8') as f:
        f.write(script)

def run_magic(exe_path: str,
              magicrc_path: str,
              script_path: str,
              log_path: str):
    args = [
        exe_path,
        '-dnull',                      #
        '-noconsole',                  #
        '-rcfile',                     #
        magicrc_path,                  #
        script_path,                   # TCL script
    ]

    info('Calling MAGIC')
    subproc(f"{' '.join(args)}, output file: {log_path}")

    rule('MAGIC Output')

    start = time.time()

    proc = subprocess.Popen(args,
                            stdin=subprocess.DEVNULL,
                            stdout=subprocess.PIPE,
                            stderr=subprocess.STDOUT,
                            universal_newlines=True,
                            text=True)
    with open(log_path, 'w', encoding='utf-8') as f:
        while True:
            line = proc.stdout.readline()
            if not line:
                break
            subproc(line[:-1])  # remove newline
            f.writelines([line])
    proc.wait()

    duration = time.time() - start

    rule()

    if proc.returncode == 0:
        info(f"MAGIC succeeded after {'%.4g' % duration}s")
    else:
        raise Exception(f"MAGIC failed with status code {proc.returncode} after {'%.4g' % duration}s, "
                        f"see log file: {log_path}")

