##
## --------------------------------------------------------------------------------
## SPDX-FileCopyrightText: 2024 Martin Jan Köhler and Harald Pretl
## Johannes Kepler University, Institute for Integrated Circuits.
##
## This file is part of KPEX 
## (see https://github.com/martinjankoehler/klayout-pex).
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
## SPDX-License-Identifier: GPL-3.0-or-later
## --------------------------------------------------------------------------------
##
name: "Publish test/coverage/lint reports to GitHub Pages"

on:
  workflow_call:
  
# NOTE: concurrency settings must be defined in calling workflow!
#       otherwise unexpected cancellations will happen
#   example error: "Canceling since a higher priority waiting request for 'martinjankoehler/klayout-pex-release-v0.1.4-Multi-platform Python/C++ build/test' exists"

jobs:
  allure-report:
    name: "Generate Allure Report (Aggregated Suites)"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      # NOTE: actions/download-artifact@v4 now has merging functionality built in => no need for actions/upload-artifact/merge@v4
      # - name: "Merge test results (Allure)"
      #   uses: actions/upload-artifact/merge@v4
      #   with:
      #     name: merged-allure-reports
      #     pattern: python-*-tests-allure-report-ubuntu*
      #     # delete-merged: true
      #     retention-days: 1

      - name: "Download and merge Allure coverage artifacts"
        uses: actions/download-artifact@v4
        with:
          pattern: python-*-tests-allure-report-*
          merge-multiple: true
          path: build/allure-results   # destination

      - name: "Set up JDK (for Allure)"
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: "Load test report history (Allure)"
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: "Build test report"
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: allure-results
          # allure_history: allure-history
          allure_results: build/allure-results
          subfolder: allure
          # subfolder: allure-results

      - name: "Publish test report"
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          destination_dir: ./
          # destination_dir: ./allure
          keep_files: true

  merge-coverage-reports:
    name: "Generate Coverage Report (Aggregated Suites)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "[🐍] Download and merge 📦 artifacts"
        uses: actions/download-artifact@v4
        with:
          pattern: python-dist-ubuntu-latest* 
          merge-multiple: true
          path: dist   # destination

      - name: "[🐍] Unpack Source 📦"
        run: |
          tar xvfz dist/klayout_pex*.tar.gz --strip-components=1
      
      - name: "[🐍] Download and merge coverage artifacts"
        uses: actions/download-artifact@v4
        with:
          pattern: python-*-tests-coverage-report-ubuntu-*
          merge-multiple: false
          path: pycov-databases   # destination

      - name: "Display structure of downloaded files"
        run: ls -R pycov-databases

      - name: "Print current working directory"
        run: pwd

      - name: "[🐍] Setup python"
        id: setup-python
        uses: actions/setup-python@v5

      - name: "[🐍] Install dependencies"
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          
      - name: "[🐍] Combine coverage reports"
        run: |
          coverage combine pycov-databases/*/python-coverage.sqlite

      - name: "[🐍] Create coverage report"
        run: |
          coverage html --directory pycov --data-file=.coverage

      - name: "Display structure of coverage report"
        run: ls -R pycov

      - name: "[🐍] Store merged coverage reports"
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: merged-coverage-report
          path: pycov
          retention-days: 1
          if-no-files-found: error

  publish-coverage-reports:
    name: "Publish Coverage Report (Aggregated Suites)"
    runs-on: ubuntu-latest
    needs: merge-coverage-reports
    steps:
      - name: "Download merged coverage artifact"
        uses: actions/download-artifact@v4
        with:
          name: merged-coverage-report
          path: pycov   # destination
    
      - name: "Publish coverage reports"
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: pycov
          destination_dir: pycov
          keep_files: true
