##
## --------------------------------------------------------------------------------
## SPDX-FileCopyrightText: 2024 Martin Jan Köhler and Harald Pretl
## Johannes Kepler University, Institute for Integrated Circuits.
##
## This file is part of KPEX 
## (see https://github.com/martinjankoehler/klayout-pex).
##
## This program is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## This program is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with this program. If not, see <http://www.gnu.org/licenses/>.
## SPDX-License-Identifier: GPL-3.0-or-later
## --------------------------------------------------------------------------------
##
name: "Publish test/coverage/lint reports to GitHub Pages"

on:
  workflow_call:
  
concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  allure-report:
    name: "Generate Allure Report (Aggregated Suites)"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      # NOTE: actions/download-artifact@v4 now has merging functionality built in => no need for actions/upload-artifact/merge@v4
      # - name: "Merge test results (Allure)"
      #   uses: actions/upload-artifact/merge@v4
      #   with:
      #     name: merged-allure-reports
      #     pattern: upload-python-allure-report-*
      #     # delete-merged: true
      #     retention-days: 1

      - name: "Download and merge Allure coverage artifacts"
        uses: actions/download-artifact@v4
        with:
          pattern: upload-python-allure-report-*
          merge-multiple: true
          path: build/allure-results   # destination
          
      - name: "Set up JDK (for Allure)"
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: "Load test report history (Allure)"
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: "Build test report"
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          gh_pages: allure-results
          # allure_history: allure-history
          allure_results: build/allure-results
          subfolder: allure
          # subfolder: allure-results

      - name: "Publish test report"
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          destination_dir: ./
          # destination_dir: ./allure
          keep_files: true

  python-coverage-report:
    name: "Generate Coverage Report (Aggregated Suites)"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: "Download and merge Python coverage artifacts"
        uses: actions/download-artifact@v4
        with:
          pattern: upload-python-coverage-report-*
          merge-multiple: true
          path: pycov   # destination
          
      - name: Display structure of downloaded files
        run: ls -R pycov
          
      - name: "Publish test report"
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: pycov
          destination_dir: pycov
          keep_files: true
