name: "Publish distribution 📦s to PyPI/TestPyPI"

on:
  workflow_call:
  
concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish-test-pypi:
    name: "Publish distribution 📦s to TestPyPI"
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: "Download and merge Python dist artifacts"
        uses: actions/download-artifact@v4
        with:
          pattern: python-dist-*
          merge-multiple: true
          path: dist   # destination

      - name: "List dist directory"
        run: find dist
      
      - uses: pypa/gh-action-pypi-publish@release/v1
        # continue-on-error: true   # might fail if we don't bump the version
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          attestations: false

